### ISSUE TITLE
gstreamer command for windows

### ISSUE THREAD

**Issue by panky0** [emlid/navio2-docs#10]
I believe it's:
gst-launch-1.0 -v udpsrc port=9000 caps=**"**application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264**"** ! rtph264depay ! avdec_h264 ! videoconvert ! autovideosink sync=f
instead of
gst-launch-1.0 -v udpsrc port=9000 caps='application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264' ! rtph264depay ! avdec_h264 ! videoconvert ! autovideosink sync=f

at least for me the pipeline didn't work with ' instead of " after caps=  
 (using gstreamer v1.8.0 for windows )

**Comment by ivnsmirnov** [comment]
@panky0, thank you for report. This information was added to Emlid documentation.

**Comment by staroselskii** [comment]
Closed with #12
