### ISSUE TITLE
Navio 2 - ADC plug

### ISSUE THREAD

**Issue by RMFPV** [emlid/navio2-docs#47]
ADC plug is never explained in the manual.

There is now mention of type of the plugs used too.

**Comment by staroselskii** [comment]
Could you please elaborate on this issue on our [forum](https://community.emlid.com)?

**Comment by RMFPV** [comment]
Your link doesn't lead anywhere. But I don't want to elaborate  anything, since I've bought an expensive controller and I want to see full info in the manual, without waisting my time for elaborating something at forums. Sorry but this is not professional customer support.
We were going to use this controller for a commercial drones production, and this is definitely not how I would like to see it.

**Comment by staroselskii** [comment]
Sorry for the wrong link. I fixed it.

I guess you should have a look at this [entry](https://docs.emlid.com/navio2/dev/pinout/). Hope, this helps. It describes the pinout of the DF13 port on your Navio 2.
